// Code generated by "stringer -type=LogicalOperations -output=logical_operations_string.go"; DO NOT EDIT.

package expression

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OR-0]
	_ = x[AND-1]
}

const _LogicalOperations_name = "ORAND"

var _LogicalOperations_index = [...]uint8{0, 2, 5}

func (i LogicalOperations) String() string {
	if i < 0 || i >= LogicalOperations(len(_LogicalOperations_index)-1) {
		return "LogicalOperations(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogicalOperations_name[_LogicalOperations_index[i]:_LogicalOperations_index[i+1]]
}
