// Code generated by "stringer -type=tokenType -output=token_type_string.go"; DO NOT EDIT.

package expression

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[symbol-0]
	_ = x[variable-1]
	_ = x[logicalOperation-2]
	_ = x[endOfExpression-3]
}

const _tokenType_name = "symbolvariablelogicalOperationendOfExpression"

var _tokenType_index = [...]uint8{0, 6, 14, 30, 45}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
